controlplanes:
  hosts:
    control-plane:
      ansible_host: 192.168.0.140

workers:
  hosts:
    worker-fred:
      ansible_host: 192.168.0.141
    worker-neves:
      ansible_host: 192.168.0.142
    worker-neon:
      ansible_host: 192.168.0.143

network:
  children:
    controlplanes:
    workers:

all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'