# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = { 'control-plane' => 1, 'worker-fred' => 1, 'worker-neves' => 1, 'worker-neon' => 1 }

Vagrant.configure('2') do |config|
  index = 0
  vms.each do |vm_name, count|
    count.times do |i|
      config.vm.define "#{vm_name}" do |node|
        node.vm.box = 'ubuntu/mantic64'
        node.vm.hostname = "#{vm_name}"
        node.vm.network 'public_network', ip: sprintf("192.168.0.14%d", index), bridge: 'enp5s0'
        node.vm.synced_folder 'shared', '/cluster_storage'
        node.vm.synced_folder "node_storage_#{vm_name}", '/node_storage'
        if vm_name == 'control-plane'
          node.vm.provider 'virtualbox' do |vb|
            vb.cpus = 1
            vb.memory = '2048'
          end
          node.vm.provision 'shell', inline: <<-SHELL
            cat /cluster_storage/outer_authorized_keys > ~/.ssh/authorized_keys
            apt-get update -y
            apt-get install -y net-tools
          SHELL
        else
          node.vm.provider 'virtualbox' do |vb|
            vb.cpus = 1
            vb.memory = '4096'
          end
          node.vm.provision 'shell', inline: <<-SHELL
            cat /cluster_storage/outer_authorized_keys > ~/.ssh/authorized_keys
            apt-get update -y
            apt-get install -y net-tools
          SHELL
        end
        index += 1
      end
    end
  end
end
