- name: Ping all nodes
  ansible.builtin.ping:

- name: Configurar nomes de domínio (DNS manual)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop:
    - "192.168.0.140 control-plane"
    - "192.168.0.170 cabine-jenkins"
    - "192.168.0.201 worker-fred"
    - "192.168.0.202 worker-neves"
    - "192.168.0.203 worker-neon"

- name: Atualizar todos os pacotes
  apt:
   name: "*"
   state: latest
   update_cache: yes

- name: Instalar pacotes essenciais
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - net-tools